name: Run Selenide Tests Daily

on:
  schedule:
    #- cron: '0 0 * * *'  # 매일 오전 9시 (한국 시간 = UTC+9 → UTC 자정 기준)
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests with Debug Logging
        run: mvn clean test -Dselenide.logging=FINE # Selenide 상세 로그 활성화 (Maven 옵션)

      - name: Save Screenshots on Failure
        if: failure()
        run: |
          mkdir -p build/screenshots
          cp -r target/selenide/screenshots/* build/screenshots/
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: build/screenshots

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/
